spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/civicconnect}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tarun@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

resend.api.key=${RESEND_API_KEY:re_LC6auULn_PyGdwew6qiiSXjdfQmVPFgzQ}