spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/civicconnect}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tarun@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a9e864001@smtp-brevo.com
spring.mail.password=mMNawGc3LV0p2YOK
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true